#!/usr/bin/env node

import chalk from "chalk";
import fs from "fs";
import {execSync} from "child_process";

console.log(chalk.cyan("[githook] post-push invoked"));

function getVersion(ref) {
  try {
    const pkg = execSync(`git show ${ref}:package.json`, { encoding: 'utf8' });
    return JSON.parse(pkg).version;
  } catch (err) {
    return null;
  }
}

const currentVersion = JSON.parse(fs.readFileSync('package.json', 'utf8')).version;
const previousVersion = getVersion('HEAD^');

if (previousVersion === currentVersion) {
  console.log(chalk.yellow('Version unchanged; skipping npm publish.'));
  process.exit(0);
}

console.log(chalk.green(`Version changed from ${previousVersion || 'none'} to ${currentVersion}. Publishing to npm...`));

try {
  execSync('npm publish', { stdio: 'inherit' });
} catch (err) {
  console.error(chalk.red('npm publish failed.'));
  process.exit(err.status || 1);
}
