#!/usr/bin/env node

import {spawn} from "child_process";

console.log('Building project...')

let testProcess = spawn('npm', ['run', 'build'], {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'inherit'
});

const kill = () => testProcess.kill('SIGINT');

process.once('SIGINT', kill);       // Ctrl-C and other events should kill the child too

process.once('SIGTERM', kill);

testProcess.on('exit', function (code) {

    console.log('build exited with code ' + code?.toString());

    if (0 !== code) {

        process.exit(code ?? 1)

    }

});




