import fs from "fs";
import os from "os";
import path from "path";
import { spawnSync } from "child_process";
import { describe, expect, it } from "vitest";

const repoRoot = process.cwd();
const generatorScriptPath = path.resolve(repoRoot, "scripts/generateRestBindings.cjs");
let generatorBuiltForTestRun = false;
const minimalSchemaDump = `CREATE TABLE \`actor\` (
  \`actor_id\` int NOT NULL AUTO_INCREMENT,
  \`first_name\` varchar(45) NOT NULL,
  PRIMARY KEY (\`actor_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;`;

const schemaDumpWithTrigger = `${minimalSchemaDump}

/*!50003 CREATE*/ /*!50017 DEFINER=\`root\`@\`localhost\`*/ /*!50003 TRIGGER \`actor_set_first_name\` BEFORE INSERT ON \`actor\` FOR EACH ROW BEGIN
  IF NEW.first_name IS NULL THEN
    SET NEW.first_name = 'UNKNOWN';
  END IF;
END */;;`;

const minimalPostgresSchemaDump = `CREATE TABLE public.actor (
    actor_id integer NOT NULL,
    first_name character varying(45) NOT NULL,
    last_name text,
    active boolean DEFAULT true NOT NULL,
    profile jsonb,
    created_at timestamp without time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.film_actor (
    actor_id integer NOT NULL,
    film_id integer NOT NULL
);

ALTER TABLE ONLY public.actor
    ADD CONSTRAINT actor_pkey PRIMARY KEY (actor_id);

ALTER TABLE public.actor ALTER COLUMN actor_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.actor_actor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.film_actor
    ADD CONSTRAINT film_actor_actor_fk FOREIGN KEY (actor_id) REFERENCES public.actor(actor_id);
`;

const ensureGeneratorScript = () => {
    if (generatorBuiltForTestRun && fs.existsSync(generatorScriptPath)) {
        return;
    }

    const build = spawnSync("npm", ["run", "build:generateRestBindings"], {
        cwd: repoRoot,
        encoding: "utf-8",
    });

    if (build.status !== 0) {
        throw new Error(
            `Failed to build generateRestBindings.cjs:\n${build.stdout ?? ""}\n${build.stderr ?? ""}`,
        );
    }

    generatorBuiltForTestRun = true;
};

const makeTempDir = (): string =>
    fs.mkdtempSync(path.join(os.tmpdir(), "carbonnode-generate-config-"));

const writeJson = (filePath: string, payload: Record<string, any>) => {
    fs.writeFileSync(filePath, `${JSON.stringify(payload, null, 2)}\n`);
};

const runGenerator = (args: string[], cwd: string) => {
    ensureGeneratorScript();
    const result = spawnSync("node", [generatorScriptPath, ...args], {
        cwd,
        encoding: "utf-8",
        env: {
            ...process.env,
            FORCE_COLOR: "0",
            C6_SKIP_GENERATED_TSC: "1",
        },
    });

    return {
        status: result.status ?? 1,
        output: `${result.stdout ?? ""}\n${result.stderr ?? ""}`,
    };
};

describe("generateRestBindings config validation", () => {
    it("fails on duplicate aliases", () => {
        const tempDir = makeTempDir();
        try {
            const configPath = path.join(tempDir, "rest.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["app"],
                    },
                    {
                        alias: "app",
                        host: "127.0.0.2",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["billing"],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", path.join(tempDir, "out")],
                tempDir,
            );

            expect(status).not.toBe(0);
            expect(output).toMatch(/Duplicate database alias 'app'/i);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("fails on alias identifier collisions after sanitization", () => {
        const tempDir = makeTempDir();
        try {
            const configPath = path.join(tempDir, "rest.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app-main",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["app"],
                    },
                    {
                        alias: "app_main",
                        host: "127.0.0.2",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["billing"],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", path.join(tempDir, "out")],
                tempDir,
            );

            expect(status).not.toBe(0);
            expect(output).toMatch(/duplicate identifier/i);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("fails when pass and passEnv are both missing", () => {
        const tempDir = makeTempDir();
        try {
            const configPath = path.join(tempDir, "rest.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        dbnames: ["app"],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", path.join(tempDir, "out")],
                tempDir,
            );

            expect(status).not.toBe(0);
            expect(output).toMatch(/must provide either 'pass' or 'passEnv'/i);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("fails on empty dbnames", () => {
        const tempDir = makeTempDir();
        try {
            const configPath = path.join(tempDir, "rest.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: [],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", path.join(tempDir, "out")],
                tempDir,
            );

            expect(status).not.toBe(0);
            expect(output).toMatch(/must provide 'dbname' or a non-empty 'dbnames' array/i);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("fails when primaryAlias does not exist", () => {
        const tempDir = makeTempDir();
        try {
            const configPath = path.join(tempDir, "rest.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["app"],
                    },
                ],
                primaryAlias: "billing",
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", path.join(tempDir, "out")],
                tempDir,
            );

            expect(status).not.toBe(0);
            expect(output).toMatch(/primaryAlias 'billing' was not found/i);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("discovers C6.config.json by walking parent directories", () => {
        const tempDir = makeTempDir();
        try {
            const nestedDir = path.join(tempDir, "nested", "deeper");
            const outputDir = path.join(tempDir, "generated");
            fs.mkdirSync(nestedDir, { recursive: true });
            fs.mkdirSync(outputDir, { recursive: true });
            fs.mkdirSync(path.join(outputDir, "C6.generated"), { recursive: true });
            fs.writeFileSync(path.join(outputDir, "C6.js"), "stale");
            fs.writeFileSync(path.join(outputDir, "C6.generated", "core.js"), "stale");
            fs.writeFileSync(
                path.join(outputDir, "C6.mysqldump.sql"),
                minimalSchemaDump,
            );

            writeJson(path.join(tempDir, "C6.config.json"), {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 3306,
                        user: "root",
                        pass: "password",
                        dbnames: ["sakila"],
                    },
                ],
                customImports: 'import type { CustomRestContext } from "./restCustomTypes";',
            });

            const { status, output } = runGenerator(
                ["--output", outputDir],
                nestedDir,
            );

            expect(status).toBe(0);
            expect(output).toMatch(/Successfully created CarbonORM bindings/i);
            const generatedC6Path = path.join(outputDir, "C6.ts");
            const generatedCorePath = path.join(outputDir, "C6.generated", "core.ts");
            const generatedScopedPath = path.join(outputDir, "C6.generated", "scoped.ts");
            const generatedActorPath = path.join(outputDir, "C6.generated", "tables", "Actor.ts");
            expect(fs.existsSync(generatedC6Path)).toBe(true);
            expect(fs.existsSync(path.join(outputDir, "C6.js"))).toBe(false);
            expect(fs.existsSync(path.join(outputDir, "C6.generated", "core.js"))).toBe(false);
            expect(fs.existsSync(generatedCorePath)).toBe(true);
            expect(fs.existsSync(generatedScopedPath)).toBe(true);
            expect(fs.existsSync(generatedActorPath)).toBe(true);
            expect(fs.readFileSync(generatedC6Path, "utf-8")).toMatch(
                /SCOPED_C6_BY_DATABASE/,
            );
            expect(fs.readFileSync(generatedActorPath, "utf-8")).toMatch(
                /registerC6Table\(/,
            );
            expect(fs.readFileSync(generatedActorPath, "utf-8")).toMatch(
                /from "\.\.\/\.\.\/restCustomTypes"/,
            );
            expect(fs.readFileSync(generatedScopedPath, "utf-8")).toMatch(
                /from "\.\.\/restCustomTypes"/,
            );
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("discovers C6.config.ts and supports async default export", () => {
        const tempDir = makeTempDir();
        try {
            const nestedDir = path.join(tempDir, "nested", "deeper");
            const outputDir = path.join(tempDir, "generated");
            fs.mkdirSync(nestedDir, { recursive: true });
            fs.mkdirSync(outputDir, { recursive: true });
            fs.writeFileSync(
                path.join(outputDir, "C6.mysqldump.sql"),
                minimalSchemaDump,
            );

            fs.writeFileSync(
                path.join(tempDir, "C6.config.ts"),
                `export default async () => ({
  databases: [
    {
      alias: "app",
      host: "127.0.0.1",
      port: 3306,
      user: "root",
      pass: "password",
      dbnames: ["sakila"]
    }
  ]
});
`,
            );

            const { status, output } = runGenerator(
                ["--output", outputDir],
                nestedDir,
            );

            expect(status).toBe(0);
            expect(output).toMatch(/Successfully created CarbonORM bindings/i);
            const generatedC6Path = path.join(outputDir, "C6.ts");
            expect(fs.existsSync(generatedC6Path)).toBe(true);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("includes table trigger DDL and metadata in generated table bindings", () => {
        const tempDir = makeTempDir();
        try {
            const outputDir = path.join(tempDir, "generated");
            fs.mkdirSync(outputDir, { recursive: true });
            fs.writeFileSync(
                path.join(outputDir, "C6.mysqldump.sql"),
                schemaDumpWithTrigger,
            );

            const configPath = path.join(tempDir, "C6.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        host: "127.0.0.1",
                        port: 1,
                        user: "root",
                        pass: "password",
                        dbnames: ["sakila"],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", outputDir, "--includeTriggerDefinitions", "1"],
                tempDir,
            );

            expect(status).toBe(0);
            expect(output).toMatch(/Successfully created CarbonORM bindings/i);

            const generatedActorPath = path.join(outputDir, "C6.generated", "tables", "Actor.ts");
            const actorSource = fs.readFileSync(generatedActorPath, "utf-8");
            expect(actorSource).toMatch(/CREATE(?: DEFINER=`root`@`localhost`)? TRIGGER `actor_set_first_name`/);
            expect(actorSource).toContain("TRIGGER_NAME: \"actor_set_first_name\"");
            expect(actorSource).toContain("EVENT_MANIPULATION: \"INSERT\"");
            expect(actorSource).toContain("ACTION_TIMING: \"BEFORE\"");
            expect(actorSource).toContain("EVENT_OBJECT_TABLE: \"actor\"");
            expect(actorSource).toContain("SET NEW.first_name = 'UNKNOWN'");
            expect(actorSource).not.toMatch(/[ \t]+$/m);

            const generatedMetadata = JSON.parse(
                fs.readFileSync(path.join(outputDir, "C6.mysqldump.json"), "utf-8"),
            );
            const actorMetadata = Object.values(generatedMetadata.TABLES as Record<string, any>)
                .find((table: any) => table.TABLE_NAME === "actor") as any;
            expect(actorMetadata.TRIGGERS).toMatchObject([
                {
                    TRIGGER_NAME: "actor_set_first_name",
                    EVENT_MANIPULATION: "INSERT",
                    ACTION_TIMING: "BEFORE",
                    EVENT_OBJECT_TABLE: "actor",
                    DEFINER: "`root`@`localhost`",
                },
            ]);
            expect(actorMetadata.TRIGGERS[0].ACTION_STATEMENT).toContain("SET NEW.first_name");
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("generates bindings from a PostgreSQL dump when dialect is postgresql", () => {
        const tempDir = makeTempDir();
        try {
            const outputDir = path.join(tempDir, "generated");
            fs.mkdirSync(outputDir, { recursive: true });
            fs.writeFileSync(
                path.join(outputDir, "C6.pg_dump.sql"),
                minimalPostgresSchemaDump,
            );

            const configPath = path.join(tempDir, "C6.config.json");
            writeJson(configPath, {
                databases: [
                    {
                        alias: "app",
                        dialect: "postgresql",
                        host: "127.0.0.1",
                        user: "postgres",
                        pass: "password",
                        dbnames: ["appdb"],
                    },
                ],
            });

            const { status, output } = runGenerator(
                ["--config", configPath, "--output", outputDir],
                tempDir,
            );

            expect(status).toBe(0);
            expect(output).toMatch(/Successfully created CarbonORM bindings/i);

            const generatedActorPath = path.join(outputDir, "C6.generated", "tables", "Actor.ts");
            const generatedFilmActorPath = path.join(outputDir, "C6.generated", "tables", "Film_Actor.ts");
            expect(fs.existsSync(generatedActorPath)).toBe(true);
            expect(fs.existsSync(generatedFilmActorPath)).toBe(true);

            const actorSource = fs.readFileSync(generatedActorPath, "utf-8");
            expect(actorSource).toMatch(/TABLE_NAME: 'actor'/);
            expect(actorSource).toMatch(/'actor_id'\?: number/);
            expect(actorSource).toMatch(/'first_name'\?: string/);
            expect(actorSource).toMatch(/'profile'\?: any \| null/);
            expect(actorSource).toMatch(/MYSQL_TYPE: 'int'/);
            expect(actorSource).toMatch(/MYSQL_TYPE: 'jsonb'/);
            expect(actorSource).toMatch(/'actor\.actor_id': \{\s*MYSQL_TYPE: 'int',\s*MAX_LENGTH: '',\s*AUTO_INCREMENT: true/);
            expect(actorSource).toMatch(/PRIMARY_SHORT: \[\s*'actor_id'/);
            expect(actorSource).toMatch(/TABLE_REFERENCED_BY: \{\s*'actor_id': \[\{/);

            const filmActorSource = fs.readFileSync(generatedFilmActorPath, "utf-8");
            expect(filmActorSource).toMatch(/TABLE_REFERENCES: \{\s*'actor_id': \[\{/);
            expect(filmActorSource).toMatch(/CONSTRAINT: 'film_actor_actor_fk'/);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });

    it("discovers .C6.ts by walking parent directories", () => {
        const tempDir = makeTempDir();
        try {
            const nestedDir = path.join(tempDir, "nested", "deeper");
            const outputDir = path.join(tempDir, "generated");
            fs.mkdirSync(nestedDir, { recursive: true });
            fs.mkdirSync(outputDir, { recursive: true });
            fs.writeFileSync(
                path.join(outputDir, "C6.mysqldump.sql"),
                minimalSchemaDump,
            );

            fs.writeFileSync(
                path.join(tempDir, ".C6.ts"),
                `export default {
  databases: [
    {
      alias: "app",
      host: "127.0.0.1",
      port: 3306,
      user: "root",
      pass: "password",
      dbnames: ["sakila"]
    }
  ]
};
`,
            );

            const { status, output } = runGenerator(
                ["--output", outputDir],
                nestedDir,
            );

            expect(status).toBe(0);
            expect(output).toMatch(/Successfully created CarbonORM bindings/i);
            expect(fs.existsSync(path.join(outputDir, "C6.ts"))).toBe(true);
        } finally {
            fs.rmSync(tempDir, { recursive: true, force: true });
        }
    });
});

describe('generator security boundaries', () => {
    it('uses argv for database names, keeps credentials temporary, and hides trigger bodies by default', () => {
        ensureGeneratorScript();
        const dir = makeTempDir();
        try {
            const bin = path.join(dir, 'bin');
            const outputDir = path.join(dir, 'out');
            fs.mkdirSync(bin); fs.mkdirSync(outputDir);
            const capture = path.join(dir, 'capture.json');
            // A fake client records arguments and permissions without using real credentials or databases.
            fs.writeFileSync(path.join(bin, 'mysqldump'), `#!/usr/bin/env node\nconst fs = require('fs');\nconst cnf = process.argv.find(v => v.startsWith('--defaults-extra-file=')).split('=').slice(1).join('=');\nfs.writeFileSync(${JSON.stringify(capture)}, JSON.stringify({argv: process.argv.slice(2), cnf, mode: fs.statSync(cnf).mode & 511}));\nprocess.stdout.write(${JSON.stringify(schemaDumpWithTrigger)});\n`, {mode: 0o755});
            fs.writeFileSync(path.join(bin, 'mysql'), '#!/bin/sh\nexit 1\n', {mode: 0o755});
            const marker = path.join(dir, 'injected');
            const dbname = `sakila; touch ${marker} #`;
            const configPath = path.join(dir, 'config.json');
            writeJson(configPath, {databases: [{alias: 'app', host: 'localhost', user: 'test', pass: 'test-only', dbname}]});
            const result = spawnSync(process.execPath, [generatorScriptPath, '--config', configPath, '--output', outputDir], {
                cwd: dir, encoding: 'utf8', env: {...process.env, PATH: `${bin}${path.delimiter}${process.env.PATH}`, C6_SKIP_GENERATED_TSC: '1'},
            });
            expect(result.status, result.stderr).toBe(0);
            expect(fs.existsSync(marker)).toBe(false);
            const record = JSON.parse(fs.readFileSync(capture, 'utf8'));
            expect(record.argv).toContain(dbname);
            expect(record.mode).toBe(0o600);
            expect(fs.existsSync(record.cnf)).toBe(false);
            expect(fs.readdirSync(outputDir).some(name => name.endsWith('.cnf'))).toBe(false);
            const actor = fs.readFileSync(path.join(outputDir, 'C6.generated/tables/Actor.ts'), 'utf8');
            expect(actor).toContain('actor_set_first_name');
            expect(actor).not.toContain('SET NEW.first_name');
            expect(actor).not.toContain('root`@`localhost');
        } finally {fs.rmSync(dir, {recursive: true, force: true});}
    });

    it('honors no-db without invoking clients or changing the existing dump', () => {
        const dir = makeTempDir();
        try {
            const outputDir = path.join(dir, 'out'); fs.mkdirSync(outputDir);
            const dumpPath = path.join(outputDir, 'C6.mysqldump.sql');
            fs.writeFileSync(dumpPath, minimalSchemaDump);
            const configPath = path.join(dir, 'config.json');
            writeJson(configPath, {databases: [{alias: 'app', host: 'invalid.example', user: 'test', pass: 'test-only', dbname: 'app'}]});
            const result = runGenerator(['--config', configPath, '--output', outputDir, '--no-db', '1', '--prefix', "x';globalThis.injected=true;//"], dir);
            expect(result.status, result.output).toBe(0);
            expect(fs.readFileSync(dumpPath, 'utf8')).toBe(minimalSchemaDump);
            expect(result.output).not.toContain('Successfully created C6.mysql.cnf');
            const core = fs.readFileSync(path.join(outputDir, 'C6.generated/core.ts'), 'utf8');
            expect(core).toContain(`export const RestTablePrefix = ${JSON.stringify("x';globalThis.injected=true;//")};`);
        } finally {fs.rmSync(dir, {recursive: true, force: true});}
    });
});
